### ISSUE TITLE
Will not build for release on Android

### ISSUE THREAD

**Issue by Rehubbard** [twilio/TwilioChatJsReactNative#18] opened 2018-06-26 06:47 UTC
When building for release on Android, I run into this error that crashes the app:

![strict mode](https://user-images.githubusercontent.com/15853085/41893967-0ab23df6-78e3-11e8-9eb2-6f0947b34879.png)

I have narrowed it down to the twilio-chat library causing this issue (when I remove the import statement the error goes away). Any idea what is happening here?

It seems to work fine when running the Android app in debug mode, but when building for production the app crashes with this error. Any help or advice would be greatly appreciated!

**Comment by aleksandrsivanovs** [comment] 2018-06-26 12:02
seems like that's not exactly twilio-chat problem: 
https://github.com/facebook/react-native/issues/11389

i'll try to sort it out today, but can't promise

**Comment by aleksandrsivanovs** [comment] 2018-07-06 13:46
Hi, @Rehubbard!

can you, please try to build with twilio-chat@3.0.2-rc1?
We have built release candidate and would really appreciate if you could tell does it solve your problem.

Aleksandrs

**Comment by aleksandrsivanovs** [comment] 2018-09-17 10:16
since there was no reply and I can't reproduce this issue anymore - closing the ticket.

**Closed as completed by aleksandrsivanovs** 2018-09-17 10:16 UTC
