### ISSUE TITLE
Slow Response chat client

### ISSUE THREAD

**Issue by ssljivic** [twilio/TwilioChatJsReactNative#27] opened 2019-05-07 15:54 UTC
We have a problem with slow Twilio response when we try to retrieve channels and messages using the following Twilio SDK methods:

chatClient.getChannelBySid (channelId)
chatClient.getLocalChannels ({crit: ‘lastMessage’, order: ‘descending’})
channel.getMessages (5)

We are not sure which method creates a problem, but it happens that the entire UI freezes while executing the code section in which these methods are called. We have also tried the Twilio demo application and noticed the same behavior:

https://github.com/twilio/TwilioChatJsReactNative

The performance issue happens even if we try to fetch 10 or 20 messages and can take up to 10 seconds or more.

Can you please help with this issue as it is making the whole application unusable?

Thanks

**Comment by aleksandrsivanovs** [comment] 2019-05-08 07:46
Hi!

what is the version of twilio-chat you are using?

**Comment by ssljivic** [comment] 2019-05-08 09:12
Hi @aleksandrsivanovs , the versions are given below:

```
"twilio-chat": "^3.2.0",
"twilio-common": "^0.1.7", 
```

**Comment by x0fma** [comment] 2019-05-19 11:01
Hi, @aleksandrsivanovs any updates ? 

I'm facing the same issue while only making ```client.create(token)``` and not fetching any channel.

Tried to play with differents twilio version above 3.0.2 (to latest 3.2.3) and UI freezes for any version. I'm also getting a related ```Unhandled promise rejection``` error with no further explanation message provided.

**Comment by aleksandrsivanovs** [comment] 2019-05-19 20:12
Hi!

Will check first thing tomorrow (Monday morning).
Sorry, haven't really had time last week.

@x0fma does UI also freeze in your case or is it overall slowliness?
Out of curiosity - do you have logging turned on? 
Does it repro with turned off logging?
(It's just that I can't see (purely analytically) how the JS code running on RN could stale main thread - that's the only reason for UI freezing, afaik).



Aleksandrs

**Comment by aleksandrsivanovs** [comment] 2019-05-20 21:25
I've upgraded to latest RN and upped all dependencies. 
Tried both debug and release (on both iOS and Android) - haven't seen any freezes.

please check this PR: https://github.com/twilio/TwilioChatJsReactNative/pull/28

**Comment by sachithkadamba** [comment] 2019-06-14 07:10
@ssljivic Hi, Has your issue has been resolved with the latest version of RN and twilio?

**Comment by arthedza** [comment] 2020-02-05 11:52
I have the same issue + this one: https://github.com/twilio/TwilioChatJsReactNative/issues/39

**Comment by joelworsham** [comment] 2020-07-06 23:39
Same here... UI freezes forever. Not usable :/ `client.getUserChannelDescriptors()` is what I'm calling before it freezes

**Comment by askel4dd** [comment] 2020-07-23 13:09
@joelworsham @arthedza Can you please provide package.json and maybe some reproduction steps? I don't have such problem and cannot reproduce it

**Comment by jeanverster** [comment] 2020-10-15 08:50
Hi everyone, I had this same issue when trying to call `client.create()`, the app would just freeze and become totally unresponsive while the memory usage just skyrockets indefinitely. This was with remote debugging DISABLED. As soon as I enabled remote debugging, the client resolved and it started working. I realised then that there must be some something in the client.create method which didn't play nice with JSC - I took a wild guess and removed all logs I had where I was logging anything coming back from the chat sdk (messages, channel, client etc) and then things started working.. Hopefully this helps someone else

**Comment by berkus** [comment] 2020-12-03 10:53
@jeanverster Correct, you should not attempt to log twilio Chat objects into RN logging systems - it seems to want to  eagerly follow the links and some of them are recursive between Chat objects. Leading to endless logging loop - which eats cpu and memory and blocks the app.

**Comment by neilanthonyte** [comment] 2022-07-07 12:53
any solution to this? Seem this request `client.getChannelByUniqueName` is also taking too long to respond.

**Comment by Pavel-Cherentsov** [comment] 2022-07-08 13:37
Hi @neilanthonyte!
How long is your `client.getChannelByUniqueName()`  request execution delay?

Region you are connecting from, cpu/mem limits of the device you're using, and quality of your internet connection can impact how long it takes for method calls to succeed.

**Closed as completed** 2022-07-27 08:30 UTC
